config/routes.rb
Rails.application.routes.draw do
  resources :preferences do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/preference.rb
class Preference < ApplicationRecord
  validates :color, presence: true

  belongs_to :user

  # broadcasts_to 'preferences', target: 'preferences'
  after_create_commit -> { broadcast_append_to user }
  after_update_commit -> { broadcast_replace_to user }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :preferences
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.first_or_create(first: 'Brad')
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :set_preference, only: %i[ show edit update destroy ]

  # GET /preferences or /preferences.json
  def index
    @preferences = current_user.preferences
  end

  def search
    if params.has_key?(:term)
      @preferences = Preference.where("color like ?", "%#{params[:term]}%")
    else
      @preferences = []
    end
  end

  # GET /preferences/1 or /preferences/1.json
  def show
  end

  # GET /preferences/new
  def new
    @preference = current_user.preferences.build
  end

  # GET /preferences/1/edit
  def edit
  end

  # POST /preferences or /preferences.json
  def create
    @preference = current_user.preferences.build(preference_params)

    respond_to do |format|
      if @preference.save
        # format.html { redirect_to preferences_path, notice: "Preference was successfully created." }
        format.html { render partial: 'preferences/new_preference_link' }
        format.json { render :index, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preferences/1 or /preferences/1.json
  def update
    respond_to do |format|
      if @preference.update(preference_params)
        format.html { render @preference, notice: "Preference was successfully updated." }
        format.json { render :show, status: :ok, location: @preference }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferences/1 or /preferences/1.json
  def destroy
    @preference.destroy
    respond_to do |format|
      format.html { redirect_to preferences_url, notice: "Preference was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preference
      @preference = Preference.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def preference_params
      params.require(:preference).permit(:color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7Turbo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/preferences/_form.html.erb
<%= form_with(model: preference, html: {novalidate: true, class: 'row g-3 align-items-center needs-validation'}) do |form| %>
  <div class="col-auto">
    <div class="input-group has-validation">
      <%= form.text_field :color, required: true, class: 'form-control' %>

      <% if preference.errors.any? %>
        <div class="invalid-feedback">
          <%= preference.errors.full_messages.join %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-auto">
    <%= form.submit class: 'btn btn-sm btn-primary' %>
    <%= link_to preference do %>
      <button class="btn btn-sm">Cancel</button>
    <% end %>
  </div>
<% end %>

app/views/preferences/_new_preference_link.html.erb
<%= turbo_frame_tag :new_preference do %>
  <%= link_to new_preference_path do %>
    <%= bootstrap_icon "plus-square-fill", width: 25, height: 25, fill: 'green' %>
  <% end %>
<% end %>

app/views/preferences/_preference.html.erb
<%= turbo_frame_tag dom_id(preference) do %>
  <div>
    <%= preference.color %>
    <%= link_to edit_preference_path(preference) do %>
      <%= bootstrap_icon "pencil-square", width: 15, height: 15, fill: 'grey' %>
    <% end %>
  </div>
<% end %>

app/views/preferences/edit.html.erb
<%= turbo_frame_tag dom_id(@preference) do %>
  <%= render "form", preference: @preference %>
<% end %>

app/views/preferences/index.html.erb
<p id="notice"><%= notice %></p>

<%= turbo_stream_from @current_user %>

<h1>Preferences</h1>

<div class="row">
  <div class="col-md-6">
    <%= turbo_frame_tag 'preferences' do %>
      <%= render @preferences %>
    <% end %>

    <%= render 'new_preference_link' %>
  </div>

  <div class="col-md-6">
    <div data-controller="colors">

      <div data-colors-target="choice"></div>

      <%= turbo_frame_tag 'search', src: search_preferences_path do %>
        <div class="spinner-border" role="status">
          <span class="sr-only"></span>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/preferences/new.html.erb
<%= turbo_frame_tag :new_preference do %>
  <%= render "form", preference: @preference %>
<% end %>

app/views/preferences/search.html.erb
<%= turbo_frame_tag 'search' do %>
  <%= form_with method: 'get', class: 'row g-3 align-items-center' do |form| %>
    <div class="col-auto">
      <%= form.text_field :term, value: params[:term], class: 'form-control' %>
    </div>
    <div class="col-auto">
      <%= form.submit 'Search', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <% @preferences.each do |preference| %>
    <div data-action="click->colors#choose">
      <%= preference.color %>
    </div>
  <% end %>
<% end %>

app/views/preferences/show.html.erb
<%= render @preference %>